name: Preparant per producció i executant ESLint
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  schedule:
    - cron: "23 21 * * 0"

jobs:
  Pujar-a-produccio-amb-SCP:
    name: Pujar a producció amb SCP i executar ESLint
    runs-on: ubuntu-latest
    steps:
      - name: Obtenint el codi del repositori
        uses: actions/checkout@v4

      - name: scp a produccio
        run: |
          echo "${{ secrets.PROD_KEY }}" > ~/prod_key.pem
          chmod 600 ~/prod_key.pem
          cd ./web/vue-actions-prod
          npm install
          npm run build
          cd ${{ github.workspace }}
          scp -r -o stricthostkeychecking=no -o UserKnownHostsFile=/dev/null -i "~/prod_key.pem" ./web/vue-actions-prod/dist/* ${{ secrets.PROD_USER }}@${{ secrets.PROD_HOST }}:/home/a21rublormar/web/rublormar-actions.daw.inspedralbes.cat/public_html/web/

      - name: Install ESLint
        run: |
          cd ./web/vue-actions-prod
          npm install eslint@8.10.0
          npm install @microsoft/eslint-formatter-sarif@2.1.7

      - name: Run ESLint
        run: |
          cd ./web/vue-actions-prod
          npm install
          npx eslint ./*

        continue-on-error: true
